var PAGES;
(function (PAGES) {
    PAGES[PAGES["INIT"] = 0] = "INIT";
    PAGES[PAGES["LIST"] = 1] = "LIST";
    PAGES[PAGES["DETAIL"] = 2] = "DETAIL";
    PAGES[PAGES["ADD"] = 3] = "ADD";
})(PAGES || (PAGES = {}));
;
var USER_STATUS;
(function (USER_STATUS) {
    USER_STATUS[USER_STATUS["INIT"] = 0] = "INIT";
    USER_STATUS[USER_STATUS["LOGGED_IN"] = 1] = "LOGGED_IN";
    USER_STATUS[USER_STATUS["ANONYMOUS"] = 2] = "ANONYMOUS";
})(USER_STATUS || (USER_STATUS = {}));
;
export { PAGES, USER_STATUS };
