export const STATUS_CODES = {
    "SUCCESS": 200,
    "BAD_RQUEST": 400,
    "UNAUTHORIZED": 401,
    "FORBIDDEN": 403,
    "NOT_FOUND": 404,
    "DUPLICATED": 409,
    "INTERNAL_SERVER_ERROR": 500,
    "NETWORK_ERROR": 503
};
export const ERROR_TYPE = {
    USER_NAME_ERROR: 0,
    NETWORK_ERROR: 1,
    ARTICLE_ID_ERROR: 2,
    SESSION_ERROR: 3,
    ARTICLE_PARAM_ERROR: 4,
    UNEXPECTED_ERROR: 5
};